const { Router } = require('express')
const { body, param } = require('express-validator')
const auth = require('../../middlewares/auth.middleware.js')
const authorize = require('../../middlewares/role.middleware.js')
const controller = require('./controller.js')

const router = Router()
router.use(auth, authorize('ADMIN'))

router.get('/users', controller.getAllUsers)
router.post('/users', [body('email').isEmail(), body('password').isLength({ min: 6 }), body('role').isIn(['ADMIN','TEACHER','STUDENT']), body('name').optional().isString()], controller.createUser)
router.put('/users/:id', [param('id').isInt(), body('email').optional().isEmail(), body('password').optional().isLength({ min: 6 }), body('role').optional().isIn(['ADMIN','TEACHER','STUDENT']), body('name').optional().isString()], controller.updateUser)
router.delete('/users/:id', [param('id').isInt()], controller.deleteUser)
router.post('/assign-student', [body('teacherId').isInt(), body('studentId').isInt()], controller.assignStudent)
router.post('/groups', [body('name').isString().isLength({ min: 1 })], controller.createGroup)
router.get('/groups', controller.getAllGroups)
router.delete('/groups/:id', [param('id').isInt()], controller.deleteGroup)
router.post('/groups/:id/members', [param('id').isInt(), body('userIds').isArray({ min: 1 })], controller.addGroupMembers)
router.delete('/groups/:id/members/:userId', [param('id').isInt(), param('userId').isInt()], controller.removeGroupMember)
router.patch('/groups/:id/settings', [param('id').isInt(), body('adminOnly').isBoolean()], controller.updateGroupSettings)
router.patch('/groups/:id/members/:userId', [param('id').isInt(), param('userId').isInt(), body('canPost').isBoolean()], controller.updateMemberPosting)
router.post('/groups/:groupId/messages/:messageId/pin', [param('groupId').isInt(), param('messageId').isInt()], controller.pinMessage)
router.delete('/groups/:groupId/messages/:messageId/pin', [param('groupId').isInt(), param('messageId').isInt()], controller.unpinMessage)

module.exports = router
